use youtuberawdata;
select s.channel_id as channel_id ,
		s.channel_title as channel_title,
        s.channel_total_hour as channel_total_hour ,
		dd.channel_video_count as channel_video_count,
        dd.channel_subscriber_count as channel_subscriber_count,
        t.url as url
from channel_info as s,channel_daliy as dd,channel_thumbnails as t
where s.channel_id =dd.channel_id 
and s.channel_id = t.channel_id 
and t.channel_thumbnails_category = 'def'
and dd.collected_date = curdate() 
and s.channel_id in ("UCgsffS7MfKL6YU3r_U3E-aA",
	"UCyn-K7rZLXjGl7VXGweIlcA",
	"UCPWFxcwPliEBMwJjmeFIDIg",
	"UCyozK5OFN5lDrwim5wqQnLA",
	"UCfpaSruWW3S4dibonKXENjA",
	"UCsNVs68quFJMaDmR6frfUsQ",
	"UCbzI92w5vWa6mEj1dACfy6g",
	"UC5XuQ-xiWAB6f-qu6gJMDBQ",
	"UCxYYbzOCCeFwAl80gDJjaag",
	"UCrxSR4OGbJBVjYxp4xjWgZQ",
	"UC31ypOxFsuU3Q0OFpQzcQ3g",
	"UCbFzvzDu17eDZ3RIeaLRswQ",
	"UCb5NLtXAsTBrmaZVhyFa-Wg",
	"UC2NFRq9s2neD_Ml0tPhNC2Q",
	"UCt15X5eHLwyP8PpNtQTkuDQ",
	"UCNzcxCN_Hh_lu5RCSFXKgGQ",
	"UCHxKSivB6JLZ1SEMdxd1fAg",
	"UCta_NRwnsUaew0t3VNxBNyg",
	"UCG7IjFUQzAxx060OjBXOveA",
	"UCSOeJWyByeoBHpmrm0NnlLw",
	"UCOmHUn--16B90oW2L6FRR3A",
	"UCLkAepWjdylmXSltofFvsYQ",
	"UCzgxx_DM2Dcb9Y1spb9mUJA",
	"UC3WZlO2Zl8NE1yIUgtwUtQw",
	"UCjwCsj-axFNcxnv3yzV22WQ",
	"UCk9GmdlDTBfgGRb7vXeRMoQ",
	"UCuhAUMLzJxlP1W7mEk0_6lA",
	"UCZqY2yIsAM9wh3vvMwKd27g",
	"UC9rMiEjNaCSsebs31MRDCRA",
	"UCzCedBCSSltI1TFd3bKyN6g");
select * from channel_daliy;						   
select channel_id,channel_view_count as '1일전' from channel_daliy
where collected_date = curdate()-1 and channel_id in ("UCgsffS7MfKL6YU3r_U3E-aA",
		"UCyn-K7rZLXjGl7VXGweIlcA",
		"UCPWFxcwPliEBMwJjmeFIDIg",
		"UCyozK5OFN5lDrwim5wqQnLA",
		"UCfpaSruWW3S4dibonKXENjA",
		"UCsNVs68quFJMaDmR6frfUsQ",
		"UCbzI92w5vWa6mEj1dACfy6g",
		"UC5XuQ-xiWAB6f-qu6gJMDBQ",
		"UCxYYbzOCCeFwAl80gDJjaag",
		"UCrxSR4OGbJBVjYxp4xjWgZQ",
		"UC31ypOxFsuU3Q0OFpQzcQ3g",
		"UCbFzvzDu17eDZ3RIeaLRswQ",
		"UCb5NLtXAsTBrmaZVhyFa-Wg",
		"UC2NFRq9s2neD_Ml0tPhNC2Q",
		"UCt15X5eHLwyP8PpNtQTkuDQ",
		"UCNzcxCN_Hh_lu5RCSFXKgGQ",
		"UCHxKSivB6JLZ1SEMdxd1fAg",
		"UCta_NRwnsUaew0t3VNxBNyg",
		"UCG7IjFUQzAxx060OjBXOveA",
		"UCSOeJWyByeoBHpmrm0NnlLw",
		"UCOmHUn--16B90oW2L6FRR3A",
		"UCLkAepWjdylmXSltofFvsYQ",
		"UCzgxx_DM2Dcb9Y1spb9mUJA",
		"UC3WZlO2Zl8NE1yIUgtwUtQw",
		"UCjwCsj-axFNcxnv3yzV22WQ",
		"UCk9GmdlDTBfgGRb7vXeRMoQ",
		"UCuhAUMLzJxlP1W7mEk0_6lA",
		"UCZqY2yIsAM9wh3vvMwKd27g",
		"UC9rMiEjNaCSsebs31MRDCRA",
		"UCzCedBCSSltI1TFd3bKyN6g"); 
select a.channel_id,
s.channel_title,
        s.channel_total_hour,
		s.channel_video_count, 
        s.channel_subscriber_count ,
        s.url,
		a.d_one, b.d_two,c.d_three,d.d_four,e.d_five
from
(select channel_id,channel_view_count as d_one from channel_daliy
where collected_date = curdate()-1 and channel_id in ("UCgsffS7MfKL6YU3r_U3E-aA",
		"UCyn-K7rZLXjGl7VXGweIlcA",
		"UCPWFxcwPliEBMwJjmeFIDIg",
		"UCyozK5OFN5lDrwim5wqQnLA",
		"UCfpaSruWW3S4dibonKXENjA",
		"UCsNVs68quFJMaDmR6frfUsQ",
		"UCbzI92w5vWa6mEj1dACfy6g",
		"UC5XuQ-xiWAB6f-qu6gJMDBQ",
		"UCxYYbzOCCeFwAl80gDJjaag",
		"UCrxSR4OGbJBVjYxp4xjWgZQ",
		"UC31ypOxFsuU3Q0OFpQzcQ3g",
		"UCbFzvzDu17eDZ3RIeaLRswQ",
		"UCb5NLtXAsTBrmaZVhyFa-Wg",
		"UC2NFRq9s2neD_Ml0tPhNC2Q",
		"UCt15X5eHLwyP8PpNtQTkuDQ",
		"UCNzcxCN_Hh_lu5RCSFXKgGQ",
		"UCHxKSivB6JLZ1SEMdxd1fAg",
		"UCta_NRwnsUaew0t3VNxBNyg",
		"UCG7IjFUQzAxx060OjBXOveA",
		"UCSOeJWyByeoBHpmrm0NnlLw",
		"UCOmHUn--16B90oW2L6FRR3A",
		"UCLkAepWjdylmXSltofFvsYQ",
		"UCzgxx_DM2Dcb9Y1spb9mUJA",
		"UC3WZlO2Zl8NE1yIUgtwUtQw",
		"UCjwCsj-axFNcxnv3yzV22WQ",
		"UCk9GmdlDTBfgGRb7vXeRMoQ",
		"UCuhAUMLzJxlP1W7mEk0_6lA",
		"UCZqY2yIsAM9wh3vvMwKd27g",
		"UC9rMiEjNaCSsebs31MRDCRA",
		"UCzCedBCSSltI1TFd3bKyN6g")) as a,
        (select channel_id,channel_view_count as d_two from channel_daliy
where collected_date = curdate()-2 and channel_id in ("UCgsffS7MfKL6YU3r_U3E-aA",
		"UCyn-K7rZLXjGl7VXGweIlcA",
		"UCPWFxcwPliEBMwJjmeFIDIg",
		"UCyozK5OFN5lDrwim5wqQnLA",
		"UCfpaSruWW3S4dibonKXENjA",
		"UCsNVs68quFJMaDmR6frfUsQ",
		"UCbzI92w5vWa6mEj1dACfy6g",
		"UC5XuQ-xiWAB6f-qu6gJMDBQ",
		"UCxYYbzOCCeFwAl80gDJjaag",
		"UCrxSR4OGbJBVjYxp4xjWgZQ",
		"UC31ypOxFsuU3Q0OFpQzcQ3g",
		"UCbFzvzDu17eDZ3RIeaLRswQ",
		"UCb5NLtXAsTBrmaZVhyFa-Wg",
		"UC2NFRq9s2neD_Ml0tPhNC2Q",
		"UCt15X5eHLwyP8PpNtQTkuDQ",
		"UCNzcxCN_Hh_lu5RCSFXKgGQ",
		"UCHxKSivB6JLZ1SEMdxd1fAg",
		"UCta_NRwnsUaew0t3VNxBNyg",
		"UCG7IjFUQzAxx060OjBXOveA",
		"UCSOeJWyByeoBHpmrm0NnlLw",
		"UCOmHUn--16B90oW2L6FRR3A",
		"UCLkAepWjdylmXSltofFvsYQ",
		"UCzgxx_DM2Dcb9Y1spb9mUJA",
		"UC3WZlO2Zl8NE1yIUgtwUtQw",
		"UCjwCsj-axFNcxnv3yzV22WQ",
		"UCk9GmdlDTBfgGRb7vXeRMoQ",
		"UCuhAUMLzJxlP1W7mEk0_6lA",
		"UCZqY2yIsAM9wh3vvMwKd27g",
		"UC9rMiEjNaCSsebs31MRDCRA",
		"UCzCedBCSSltI1TFd3bKyN6g")) as b,
        (select channel_id,channel_view_count as d_three from channel_daliy
where collected_date = curdate()-3 and channel_id in ("UCgsffS7MfKL6YU3r_U3E-aA",
		"UCyn-K7rZLXjGl7VXGweIlcA",
		"UCPWFxcwPliEBMwJjmeFIDIg",
		"UCyozK5OFN5lDrwim5wqQnLA",
		"UCfpaSruWW3S4dibonKXENjA",
		"UCsNVs68quFJMaDmR6frfUsQ",
		"UCbzI92w5vWa6mEj1dACfy6g",
		"UC5XuQ-xiWAB6f-qu6gJMDBQ",
		"UCxYYbzOCCeFwAl80gDJjaag",
		"UCrxSR4OGbJBVjYxp4xjWgZQ",
		"UC31ypOxFsuU3Q0OFpQzcQ3g",
		"UCbFzvzDu17eDZ3RIeaLRswQ",
		"UCb5NLtXAsTBrmaZVhyFa-Wg",
		"UC2NFRq9s2neD_Ml0tPhNC2Q",
		"UCt15X5eHLwyP8PpNtQTkuDQ",
		"UCNzcxCN_Hh_lu5RCSFXKgGQ",
		"UCHxKSivB6JLZ1SEMdxd1fAg",
		"UCta_NRwnsUaew0t3VNxBNyg",
		"UCG7IjFUQzAxx060OjBXOveA",
		"UCSOeJWyByeoBHpmrm0NnlLw",
		"UCOmHUn--16B90oW2L6FRR3A",
		"UCLkAepWjdylmXSltofFvsYQ",
		"UCzgxx_DM2Dcb9Y1spb9mUJA",
		"UC3WZlO2Zl8NE1yIUgtwUtQw",
		"UCjwCsj-axFNcxnv3yzV22WQ",
		"UCk9GmdlDTBfgGRb7vXeRMoQ",
		"UCuhAUMLzJxlP1W7mEk0_6lA",
		"UCZqY2yIsAM9wh3vvMwKd27g",
		"UC9rMiEjNaCSsebs31MRDCRA",
		"UCzCedBCSSltI1TFd3bKyN6g")) as c,
        (select channel_id,channel_view_count as d_four from channel_daliy
where collected_date = curdate()-4 and channel_id in ("UCgsffS7MfKL6YU3r_U3E-aA",
		"UCyn-K7rZLXjGl7VXGweIlcA",
		"UCPWFxcwPliEBMwJjmeFIDIg",
		"UCyozK5OFN5lDrwim5wqQnLA",
		"UCfpaSruWW3S4dibonKXENjA",
		"UCsNVs68quFJMaDmR6frfUsQ",
		"UCbzI92w5vWa6mEj1dACfy6g",
		"UC5XuQ-xiWAB6f-qu6gJMDBQ",
		"UCxYYbzOCCeFwAl80gDJjaag",
		"UCrxSR4OGbJBVjYxp4xjWgZQ",
		"UC31ypOxFsuU3Q0OFpQzcQ3g",
		"UCbFzvzDu17eDZ3RIeaLRswQ",
		"UCb5NLtXAsTBrmaZVhyFa-Wg",
		"UC2NFRq9s2neD_Ml0tPhNC2Q",
		"UCt15X5eHLwyP8PpNtQTkuDQ",
		"UCNzcxCN_Hh_lu5RCSFXKgGQ",
		"UCHxKSivB6JLZ1SEMdxd1fAg",
		"UCta_NRwnsUaew0t3VNxBNyg",
		"UCG7IjFUQzAxx060OjBXOveA",
		"UCSOeJWyByeoBHpmrm0NnlLw",
		"UCOmHUn--16B90oW2L6FRR3A",
		"UCLkAepWjdylmXSltofFvsYQ",
		"UCzgxx_DM2Dcb9Y1spb9mUJA",
		"UC3WZlO2Zl8NE1yIUgtwUtQw",
		"UCjwCsj-axFNcxnv3yzV22WQ",
		"UCk9GmdlDTBfgGRb7vXeRMoQ",
		"UCuhAUMLzJxlP1W7mEk0_6lA",
		"UCZqY2yIsAM9wh3vvMwKd27g",
		"UC9rMiEjNaCSsebs31MRDCRA",
		"UCzCedBCSSltI1TFd3bKyN6g")) as d,
        (select channel_id,channel_view_count as d_five from channel_daliy
where collected_date = curdate()-5 and channel_id in ("UCgsffS7MfKL6YU3r_U3E-aA",
		"UCyn-K7rZLXjGl7VXGweIlcA",
		"UCPWFxcwPliEBMwJjmeFIDIg",
		"UCyozK5OFN5lDrwim5wqQnLA",
		"UCfpaSruWW3S4dibonKXENjA",
		"UCsNVs68quFJMaDmR6frfUsQ",
		"UCbzI92w5vWa6mEj1dACfy6g",
		"UC5XuQ-xiWAB6f-qu6gJMDBQ",
		"UCxYYbzOCCeFwAl80gDJjaag",
		"UCrxSR4OGbJBVjYxp4xjWgZQ",
		"UC31ypOxFsuU3Q0OFpQzcQ3g",
		"UCbFzvzDu17eDZ3RIeaLRswQ",
		"UCb5NLtXAsTBrmaZVhyFa-Wg",
		"UC2NFRq9s2neD_Ml0tPhNC2Q",
		"UCt15X5eHLwyP8PpNtQTkuDQ",
		"UCNzcxCN_Hh_lu5RCSFXKgGQ",
		"UCHxKSivB6JLZ1SEMdxd1fAg",
		"UCta_NRwnsUaew0t3VNxBNyg",
		"UCG7IjFUQzAxx060OjBXOveA",
		"UCSOeJWyByeoBHpmrm0NnlLw",
		"UCOmHUn--16B90oW2L6FRR3A",
		"UCLkAepWjdylmXSltofFvsYQ",
		"UCzgxx_DM2Dcb9Y1spb9mUJA",
		"UC3WZlO2Zl8NE1yIUgtwUtQw",
		"UCjwCsj-axFNcxnv3yzV22WQ",
		"UCk9GmdlDTBfgGRb7vXeRMoQ",
		"UCuhAUMLzJxlP1W7mEk0_6lA",
		"UCZqY2yIsAM9wh3vvMwKd27g",
		"UC9rMiEjNaCSsebs31MRDCRA",
		"UCzCedBCSSltI1TFd3bKyN6g")) as e,
        (select s.channel_id as channel_id ,
		s.channel_title as channel_title,
        s.channel_total_hour as channel_total_hour ,
		dd.channel_video_count as channel_video_count,
        dd.channel_subscriber_count as channel_subscriber_count,
        t.url as url
	from channel_info as s,channel_daliy as dd,channel_thumbnails as t
	where s.channel_id =dd.channel_id 
	and s.channel_id = t.channel_id 
	and t.channel_thumbnails_category = 'def'
	and dd.collected_date = curdate() 
	and s.channel_id in ("UCgsffS7MfKL6YU3r_U3E-aA",
	"UCyn-K7rZLXjGl7VXGweIlcA",
	"UCPWFxcwPliEBMwJjmeFIDIg",
	"UCyozK5OFN5lDrwim5wqQnLA",
	"UCfpaSruWW3S4dibonKXENjA",
	"UCsNVs68quFJMaDmR6frfUsQ",
	"UCbzI92w5vWa6mEj1dACfy6g",
	"UC5XuQ-xiWAB6f-qu6gJMDBQ",
	"UCxYYbzOCCeFwAl80gDJjaag",
	"UCrxSR4OGbJBVjYxp4xjWgZQ",
	"UC31ypOxFsuU3Q0OFpQzcQ3g",
	"UCbFzvzDu17eDZ3RIeaLRswQ",
	"UCb5NLtXAsTBrmaZVhyFa-Wg",
	"UC2NFRq9s2neD_Ml0tPhNC2Q",
	"UCt15X5eHLwyP8PpNtQTkuDQ",
	"UCNzcxCN_Hh_lu5RCSFXKgGQ",
	"UCHxKSivB6JLZ1SEMdxd1fAg",
	"UCta_NRwnsUaew0t3VNxBNyg",
	"UCG7IjFUQzAxx060OjBXOveA",
	"UCSOeJWyByeoBHpmrm0NnlLw",
	"UCOmHUn--16B90oW2L6FRR3A",
	"UCLkAepWjdylmXSltofFvsYQ",
	"UCzgxx_DM2Dcb9Y1spb9mUJA",
	"UC3WZlO2Zl8NE1yIUgtwUtQw",
	"UCjwCsj-axFNcxnv3yzV22WQ",
	"UCk9GmdlDTBfgGRb7vXeRMoQ",
	"UCuhAUMLzJxlP1W7mEk0_6lA",
	"UCZqY2yIsAM9wh3vvMwKd27g",
	"UC9rMiEjNaCSsebs31MRDCRA",
	"UCzCedBCSSltI1TFd3bKyN6g")) as s
        where a.channel_id = b.channel_id 
        and a.channel_id = c.channel_id 
        and a.channel_id = d.channel_id 
        and a.channel_id = e.channel_id
        and a.channel_id = s.channel_id;

        

	